# Generated by Django 3.1.1 on 2020-09-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=300, verbose_name='Name of city')),
                ('weather_main_description', models.CharField(blank=True, max_length=300, verbose_name='Main description')),
                ('weather_full_description', models.CharField(blank=True, max_length=300, verbose_name='Full description')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('temperature', models.IntegerField(blank=True, default=0, verbose_name='Temperature')),
                ('weather_icon', models.CharField(blank=True, default='01d', max_length=300, verbose_name='Icon')),
                ('humidity', models.IntegerField(blank=True, default=0, verbose_name='Humidity')),
                ('pressure', models.IntegerField(blank=True, default=0, verbose_name='Pressure')),
                ('wind_speed', models.IntegerField(blank=True, default=0, verbose_name='Wind speed')),
                ('country', models.CharField(blank=True, default='Unknown', max_length=300, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
