# Generated by Django 3.1.1 on 2021-06-07 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteweather', '0003_auto_20210608_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('city_name', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True, verbose_name='Name of city')),
                ('country', models.CharField(blank=True, default='Unknown', max_length=300, verbose_name='Country')),
            ],
        ),
        migrations.RemoveField(
            model_name='cityblock',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='cityblock',
            name='country',
        ),
        migrations.AddField(
            model_name='cityblock',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='siteweather.location'),
        ),
    ]
